{% set name = "lbzip2" %}
{% set version = "2.5" %}
{% set sha256 = "7be69ece83ecdc8f12b9201d838eee5cdb499f2fd68cffd2af58866076ccac43" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/kjn/lbzip2/archive/refs/tags/v{{ version }}.tar.gz
    sha256: {{ sha256 }}
     # from gnulib-devel srpms in fedora 42 - gnulib-devel-0-52.20230709git.fc42.noarch.rpm
    patches:
      - lbzip2-c99.patch
      - lbzip2-gnulib.patch

  # per lbzip2's build instructions (and as used in distro rpm specs)
  # gnulib-tool is necessary to generate the configure and Makefile.in
  # https://www.gnu.org/software/gnulib/
  - url: https://github.com/coreutils/gnulib/archive/refs/tags/v1.0.tar.gz
    folder: gnulib
    sha256: c3585637eeab2268400f26a7174862d72c416e9476a0ff4ec12ebce646a0f477


build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - automake
    - libtool
    - m4
    - make
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - wget
  run:
    - bzip2

test:
  commands:
    - lbzip2 --version | grep {{ version }}

about:
  home: http://lbzip2.org
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: lbzip2 is a free, multi-threaded compression utility with support for bzip2 compressed file format

extra:
  recipe-maintainers:
    - gqmelo
    - dslarm
