{% set name = "lbzip2" %}
{% set version = "2.5" %}
{% set sha256 = "7be69ece83ecdc8f12b9201d838eee5cdb499f2fd68cffd2af58866076ccac43" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/kjn/lbzip2/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

  patches:   # from gnulib-devel srpms in fedora 42 - gnulib-devel-0-52.20230709git.fc42.noarch.rpm
    - lbzip2-c99.patch
    - lbzip2-gnulib.patch


build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - glib-tools
    - automake
    - libtool
    - m4
    - tar
    - make
    - {{ compiler('c') }} 
    - {{ stdlib('c') }}
    - wget

test:
  requires:
    - bzip2
  commands:
    - lbzip2 --version

about:
  home: http://lbzip2.org
  license: GPLv3
  license_file: lbzip2-{{ version }}/COPYING
  summary: lbzip2 is a free, multi-threaded compression utility with support for bzip2 compressed file format

extra:
  recipe-maintainers:
    - gqmelo
