{% set name = "lbzip2" %}
{% set version = "2.5" %}
{% set sha256 = "7be69ece83ecdc8f12b9201d838eee5cdb499f2fd68cffd2af58866076ccac43" %}

package:
  name: {{ name }}
  version: {{ version }}

# UNCOMMENT AFTER THIS ISSUE IS SOLVED:
# https://github.com/conda-forge/docker-images/pull/36
# source:
#   fn: lbzip2-{{ version }}.tar.bz2
#   url: http://archive.lbzip2.org/lbzip2-{{ version }}.tar.bz2
#   sha256: {{ sha256 }}

source:
  url: https://github.com/kjn/lbzip2/archive/refs/tags/v{{ version }}.tar.gz

build:
  number: 0
  skip: True  # [win]
  script:
    - autoconf
    - ./configure --prefix=$PREFIX
    - make -j${CPU_COUNT}
    - make check         # [build_platform == target_platform]
    - make install

requirements:
  build:
    - autotools
    - openssl
    - tar
    - make
    - {{ compiler('c') }} 
    - {{ stdlib('c') }}

test:
  requires:
    - bzip2
  commands:
    - lbzip2 --version

about:
  home: http://lbzip2.org
  license: GPLv3
  license_file: lbzip2-{{ version }}/COPYING
  summary: lbzip2 is a free, multi-threaded compression utility with support for bzip2 compressed file format

extra:
  recipe-maintainers:
    - gqmelo
