{% set name = "lbzip2" %}
{% set version = "2.5" %}
{% set sha256 = "eec4ff08376090494fa3710649b73e5412c3687b4b9b758c93f73aa7be27555b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://archive.lbzip2.org/lbzip2-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: True  # [win]
  script:
    - ./configure --prefix=$PREFIX
    - make -j${CPU_COUNT}
    - make check
    - make install

requirements:
  build:
    - {{ compiler('c') }}

test:
  requires:
    - bzip2
  commands:
    - lbzip2 --version

about:
  home: http://lbzip2.org
  license: GPLv3
  license_file: COPYING
  summary: lbzip2 is a free, multi-threaded compression utility with support for bzip2 compressed file format

extra:
  recipe-maintainers:
    - gqmelo
