appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: i+6rcriF19dDlYoAEnI3GOr/a6aF/Es6RqOpqjJ9DhJK9O7bFY4dfJnoNoUXFhHxL+2pCygU0cTSucclO9bDLiC3qOQiyxy+0SG18jH05guPpb5e1ywRHVkxmuDEyVM5IfSY8LanCTZa5NLumMbU+BSwOAN4YWdCi/edm8T5DVzFhBNQ4lP/xGHvyKVBSn9vjepLw2y8c0ISV3u53S/rLNOk4UH18i764xZnhdM7JJhrtr4WteVIEQjIMjdkKFkuVaIB7Q9iY1SrchzSajpRhfJJL1yFC5XVabOgqH/y3AQxUGyF6vYoeqId25DjNpyzWGNaBmX7puR4yKl7l37lVa8Uhvo19h2OWS8icSndd/eNTpr3pmSURKUPREZ9b5iuIqXn4Ee55r3nHPFMsnp2mj7W24APTC4A88XtChwvehBesUTux3H27QBCSP11J5oy1aDmAR2jhn6CebncaOgnCOxR6si2TFhm6CXEaNihE8Qa/8FqdxGy9PoD6ZPFmGarV23PRoAgrwrXsVaY3c34rBiuXksucPjT9mQeHIPVkh3Qw7zR4zNpVFIan5gsnmciMAfa0KcrKqDVF7USdxWTzJ8kRSeHdLurZhgiK3RPees3z86ld/jAlsLnnOYNT50kaZeNxIElF+zfmZ/xlrjw6TPxifYYlnMe1iBUaoGwtas=}
